name: flutter_customer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  package_info_plus: ^8.0.0
  sentry_flutter: ^9.10.0
  skeletonizer: ^2.1.2
  supabase_flutter: ^2.12.0
  universal_platform: ^1.1.0
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  freezed: ^2.4.7
  mocktail: ^1.0.4
  mockito: ^5.4.4

flutter:
  uses-material-design: true
